# Site settings
title: Aprendizajes
author: Eloy Espinaco
author_title: Critical developer
email: eloyesp@gmail.com
description: |
  A simple blog, because it help me to learn.
  Without writing there is no learning.
baseurl: ""
url: "https://eloyesp.github.io"
twitter_username: eloyesp
github_username:  eloyesp
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
permalink: pretty
safe: true

# Serving
host: 0.0.0.0
