# Site settings
title: Aprendizajes
email: eloyesp@gmail.com
description: |
  A simple blog, because it help me to learn.
  Without writing there is no learning.
baseurl: ""
url: "http://eloyesp.github.io"
twitter_username: eloyesp
github_username:  eloyesp

# Build settings
markdown: kramdown
permalink: pretty
safe: true
